AdminModule/Areas/Admin/Pages/User/EditUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.User
{
    public class EditUserModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public Users Customer { get; set; }

        public IConfiguration Configuration { get; set; }

        public EditUserModel(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public async Task<IActionResult> OnGet(int userId)
        {
            if (userId != 0)
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Customer = await httpClient.GetFromJsonAsync<Users>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetUserById?userId={userId}");
                }
                NavSideBar();
                return Page();
            }
            else
            {
                return RedirectToPage("UsersList");
            }
        }

        public async Task<IActionResult> OnPost(string prDate, IList<int> rolesIds)
        {
            Customer.RegisterDate = DateTime.Parse(prDate);
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.DeleteAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/User/RemoveAllUserRoleByUserId?userId={Customer.UserId}");
                foreach (int roleId in rolesIds)
                {
                    await httpClient.PostAsJsonAsync<UserRequest>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/AddUserRole", new UserRequest() { UserId = Customer.UserId, RoleId = roleId });
                }
                await httpClient.PutAsJsonAsync<Users>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/UpdateUser", Customer);
            }
            Message = $"{Customer.UserName} با موفقیت ویرایش شد";
            return RedirectToPage("UsersList");
        }

        public async Task<IList<Roles>> GetUserRolesAsync(int userId)
        {
            IList<Roles> roles = new List<Roles>();
            using (HttpClient httpClient = new HttpClient())
            {
                IList<UserRoles> userRoles = await httpClient.GetFromJsonAsync<IList<UserRoles>>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetUserRolesByUserId?userId={userId}");
                foreach (UserRoles role in userRoles.ToList())
                {
                    roles.Add(await httpClient.GetFromJsonAsync<Roles>($"{Configuration.GetSection("ApiUrlAddress").Value}/Role/GetRoleById?roleId={role.RoleId}"));
                }
                return roles;
            }
        }

        public async Task<IList<Roles>> GetAllRolesAsync()
        {
            using (HttpClient httpClient = new HttpClient())
            {
                return await httpClient.GetFromJsonAsync<IList<Roles>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Role/GetRoles");
            }
        }


        private void NavSideBar()
        {
            ViewData["manageUser"] = true;
            ViewData["userList"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/User/OnlineUsers.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.User
{
    public class OnlineUsersModel : PageModel
    {
        public IList<OnlineUsers> OnlineUsers { get; set; }

        public IConfiguration Configuration { get; set; }

        public OnlineUsersModel(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public async Task OnGet()
        {
            using (HttpClient httpClient = new HttpClient())
            {
                OnlineUsers = await httpClient.GetFromJsonAsync<IList<OnlineUsers>>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetAllOnlineUsers");
            }
            NavSideBar();
        }

        private void NavSideBar()
        {
            ViewData["manageUser"] = true;
            ViewData["manageOnlineUser"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/User/UsersList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Application.ViewModels.Public;
using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.User
{
    public class UsersListModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public IList<Users> Users { get; set; }

        public IConfiguration Configuration { get; set; }

        public PaggingViewModel PaggingViewModel { get; set; }


        public UsersListModel(IConfiguration configuration, PaggingViewModel paggingViewModel)
        {
            Configuration = configuration;
            PaggingViewModel = paggingViewModel;
        }


        public async Task OnGet(string query, int pageId = 1)
        {
            if (!string.IsNullOrEmpty(query) || !string.IsNullOrWhiteSpace(query))
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Users = await httpClient.GetFromJsonAsync<IList<Users>>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/FilterUsers?query={query}&pageId={pageId}");
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(await httpClient.GetFromJsonAsync<double>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/FilterUsersCount?query={query}") / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
                ViewData["query"] = query;
            }
            else
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Users = await httpClient.GetFromJsonAsync<IList<Users>>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetAllUsers?pageId={pageId}");
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(await httpClient.GetFromJsonAsync<double>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetAllUsersCount") / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                }
            }

            NavSideBar();
        }

        public async Task<IActionResult> OnGetDeleteUserAsync(int userId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.DeleteAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/User/DeleteUser?userId={userId}");
            }
            Message = "کاربر مورد نظر حذف شد";
            return RedirectToPage("UsersList");
        }

        public async Task<IActionResult> OnGetDisableUserAsync(int userId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.PutAsJsonAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/User/DeActiveUser", new UserRequest() { UserId = userId });
            }
            Message = "کاربر مورد نظر غیر فعال شد";
            return RedirectToPage("UsersList");
        }

        public async Task<IActionResult> OnGetEnableUserAsync(int userId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.PutAsJsonAsync
                    ($"{Configuration.GetSection("ApiUrlAddress").Value}/User/ActiveUser", new UserRequest() { UserId = userId });
            }
            Message = "کاربر مورد نظر فعال شد";
            return RedirectToPage("UsersList");
        }

        public async Task<IList<Roles>> GetUserRolesAsync(int userId)
        {
            IList<Roles> roles = new List<Roles>();
            using (HttpClient httpClient = new HttpClient())
            {
                IList<UserRoles> userRoles = await httpClient.GetFromJsonAsync<IList<UserRoles>>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetUserRolesByUserId?userId={userId}");
                foreach (UserRoles role in userRoles.ToList())
                {
                    roles.Add(await httpClient.GetFromJsonAsync<Roles>($"{Configuration.GetSection("ApiUrlAddress").Value}/Role/GetRoleById?roleId={role.RoleId}"));
                }
                return roles;
            }
        }

        private void NavSideBar()
        {
            ViewData["manageUser"] = true;
            ViewData["userList"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/User/EditUser.cshtml
@page
@model AdminModule.Areas.Admin.Pages.User.EditUserModel
@{
    ViewData["Title"] = "ویرایش کاربر";
}

<div>
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">ویرایش کاربر</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-page="/User/UsersList">مدیریت کاربران</a></li>
                        <li class="breadcrumb-item active">ویرایش کاربر</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
</div>

<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">ویرایش کاربر</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" method="post">
            <div class="card-body">
                <input type="hidden" asp-for="Customer.UserId" />
                <input type="hidden" asp-for="Customer.Password" />
                <input type="hidden" asp-for="Customer.ActiveCode" />
                <input type="hidden" asp-for="Customer.AccountBalance" />
                <div class="form-group">
                    <label asp-for="Customer.UserName"></label>
                    <input asp-for="Customer.UserName" class="form-control" placeholder="نام کاربری را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.UserName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.Name"></label>
                    <input asp-for="Customer.Name" class="form-control" placeholder="نام را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.Name"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.Family"></label>
                    <input asp-for="Customer.Family" class="form-control" placeholder="نام خانوادگی را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.Family"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.Email"></label>
                    <input asp-for="Customer.Email" class="form-control" placeholder="ایمیل کاربر را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.Email"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.Mobile"></label>
                    <input asp-for="Customer.Mobile" class="form-control" placeholder="شماره موبایل را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.Mobile"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.UserDescription"></label>
                    <input asp-for="Customer.UserDescription" class="form-control" placeholder="توضیحات کاربر را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.UserDescription"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.IsActive"></label>
                    <div class="row">
                        <input asp-for="Customer.IsActive" class="form-control w-25">
                        <label for="Customer_IsActive">وضعیت فعال / غیرفعال بودن کاربر</label>
                    </div>
                    <span class="text-danger mt-2" asp-validation-for="Customer.IsActive"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.RegisterDate"></label>
                    <input id="prDate" name="prDate" class="form-control" placeholder="تاریخ ثبت نام کاربر را وارد کنید" value="@Model.Customer.RegisterDate">
                    <span class="text-danger mt-2" asp-validation-for="Customer.RegisterDate"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.ThemeSellerPercentage"></label>
                    <input asp-for="Customer.ThemeSellerPercentage" class="form-control" placeholder="درصد فروشندگی کاربر را وارد کنید">
                    <span class="text-danger mt-2" asp-validation-for="Customer.ThemeSellerPercentage"></span>
                </div>
                <div class="form-group">
                    <label>انتخاب مقام های کاربر</label>
                    <select name="rolesIds" class="form-control select2" multiple="multiple" data-placeholder="یک مقام را انتخاب کنید" style="width: 100%;text-align: right">
                        @foreach (var role in await Model.GetAllRolesAsync())
                        {
                            bool hasRole = false;
                            foreach (var userRole in await Model.GetUserRolesAsync(Model.Customer.UserId))
                            {
                                if (role.RoleId == userRole.RoleId)
                                {
                                    hasRole = true;
                                    <option value="@userRole.RoleId" selected>@userRole.RoleTitle</option>
                                    break;
                                }
                            }
                            if (!hasRole)
                            {
                                <option value="@role.RoleId">@role.RoleTitle</option>
                            }
                        }
                    </select>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" onclick="changeDate()" class="btn btn-warning">ویرایش <i class="fa fa-edit"></i></button>
            </div>
        </form>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="~/lib/persian-datepicker/persian-datepicker.min.css" />
}

@section Scripts{
    <script src="~/lib/persian-datepicker/persian-date.min.js"></script>
    <script src="~/lib/persian-datepicker/persian-datepicker.min.js"></script>
    <script src="~/lib/jalali-moment/jalali-moment.browser.min.js"></script>
    <script>
        //change number
        String.prototype.toEnglishDigit = function () { var find = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹']; var replace = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']; var replaceString = this; var regex; for (var i = 0; i < find.length; i++) { regex = new RegExp(find[i], "g"); replaceString = replaceString.replace(regex, replace[i]); } return replaceString; };
        //end change number
        $(document).ready(function () {
            $('#prDate').pDatepicker({ format: 'LLLL'});
        });
        function changeDate() {
            $('#prDate').val(moment.from($('#prDate').val().toEnglishDigit(), 'fa', 'LLLL')
                .format('YYYY-M-D HH:mm:ss'));
        }
    </script>
    <partial name="_ValidationScriptsPartial" />
}

AdminModule/Areas/Admin/Pages/User/OnlineUsers.cshtml
@page
@model AdminModule.Areas.Admin.Pages.User.OnlineUsersModel
@{
    ViewData["Title"] = "کاربران آنلاین";
}

<div>
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">وضعیت کاربران (<span class="text-success">@(Model.OnlineUsers.Count(u => u.OnlineStatus==true))</span>)</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-page="OnlineUsers">مدیریت کاربران</a></li>
                        <li class="breadcrumb-item active">کاربران آنلاین</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <table class="table table-hover table-dark mt-4">
            <thead class="text-center">
                <tr>
                    <th scope="col">نام کاربری</th>
                    <th scope="col">آی پی (IP)</th>
                    <th scope="col">مسیر مشاهده</th>
                    <th scope="col">وضعیت</th>
                    <th scope="col">تاریخ فعالیت</th>
                </tr>
            </thead>
            <tbody id="trackUserTable">
                @foreach (var item in Model.OnlineUsers)
                {
                    <tr class="text-center">
                        <th scope="row">@item.UserName</th>
                        <td>@item.Ip</td>
                        <td class="ltr">@item.VisitPath</td>
                        @if (item.OnlineStatus)
                        {
                            <td><p class="bg-success p-2 rounde-corners">آنلاین</p></td>
                        }
                        else
                        {
                            <td><p class="bg-danger p-2 rounde-corners">آفلاین</p></td>
                        }
                        <td>@item.StartTime.ToLongShamsiDate()</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

AdminModule/Areas/Admin/Pages/User/UsersList.cshtml
@page
@model AdminModule.Areas.Admin.Pages.User.UsersListModel
@{
    ViewData["Title"] = "مدیریت کاربران";
}

<div>
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">لیست کاربران</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a asp-area="Admin" asp-page="/User/UsersList">مدیریت کاربران</a></li>
                        <li class="breadcrumb-item active">لیست کاربران</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3>لیست کاربران تم شاپ</h3>
                        <div class="card-tools">
                            <form method="get">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="query" class="form-control float-right" placeholder="جستجو" @((ViewData["query"] != null) ? $"value={ViewData["query"]}" : "")>
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <tbody>
                                <tr>
                                    <th>نام کاربری</th>
                                    <th>ایمیل</th>
                                    <th>موبایل</th>
                                    <th>وضعیت</th>
                                    <th>موجودی کاربر</th>
                                    <th>نقش های کاربر</th>
                                    <th>عملیات</th>
                                </tr>
                                @if (Model.Users != null)
                                {
                                    @foreach (var user in Model.Users)
                                    {
                                        <tr>
                                            <td>@user.UserName</td>
                                            <td>@user.Email</td>
                                            <td>@user.Mobile</td>

                                            @if (user.IsActive)
                                            {
                                                <td><span class="badge badge-success p-2">فعال</span></td>
                                            }
                                            else
                                            {
                                                <td><span class="badge badge-danger p-2">غیر فعال</span></td>
                                            }
                                            <td><span class="badge-pill badge-primary p-2">@user.AccountBalance.ToString("#,#") تومان</span></td>
                                            <td>
                                                @foreach (var userRoles in await Model.GetUserRolesAsync(user.UserId))
                                                {
                                                        <span class="badge-info m-1 rounded p-1">@userRoles.RoleTitle</span>
                                                }
                                            </td>
                                            <td>
                                                <div class="row">
                                                    <div><a asp-page="/User/EditUser" asp-route-userId="@user.UserId" class="btn btn-warning btn-sm">ویرایش <i class="fa fa-edit"></i></a></div>
                                                    @if (user.IsActive)
                                                    {
                                                        <div><a asp-page-handler="DisableUser" asp-route-userId="@user.UserId" class="btn btn-danger btn-sm mr-3" id="deleteBtn">غیر فعال <i class="fa fa-close"></i></a></div>
                                                    }
                                                    else
                                                    {
                                                        <div><a asp-page-handler="EnableUser" asp-route-userId="@user.UserId" class="btn btn-success btn-sm mr-3" id="deleteBtn">فعال <i class="fa fa-check"></i></a></div>
                                                    }
                                                    <div><a asp-page-handler="DeleteUser" asp-route-userId="@user.UserId" class="btn btn-danger btn-sm mr-3" id="deleteBtn">حذف <i class="fa fa-trash"></i></a></div>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        @await Component.InvokeAsync("PaginationComponent", Model.PaggingViewModel)
                    </div>
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
@if (!string.IsNullOrEmpty(Model.Message))
{
    <input type="hidden" id="message" value="@Model.Message" />
}

@section Scripts{
    <script>
        var message = $('#message').val(); // get the value of the message
        if (message != null && message != "") {
            swal({
                title: "کاربران",
                buttons: false,
                timer: 3000,
                text: message,
                icon: "success"
            });
        }
    </script>
}