AdminModule/Areas/Admin/Pages/Ticket/AnswerTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.Ticket
{
    public class AnswerTicketModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public Ticketings Ticket { get; set; }

        public IList<TicketMessages> TicketMessages { get; set; }

        [BindProperty]
        public TicketMessages TicketMessage { get; set; }

        public Users Sender { get; set; }

        public Users Reciver { get; set; }

        public IConfiguration Configuration { get; set; }


        public AnswerTicketModel(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public async Task<IActionResult> OnGetAsync(int ticketId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                Ticket = await httpClient.GetFromJsonAsync<Ticketings>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketById?ticketId={ticketId}");
                if (Ticket != null && Ticket.IsDelete != true)
                {
                    TicketMessages = await httpClient.GetFromJsonAsync<IList<TicketMessages>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketMessages?ticketId={ticketId}");
                    Sender = await GetUserByIdAsync(Ticket.Sender);
                    Reciver = await GetUserByIdAsync(Ticket.Reciver);
                    await httpClient.GetFromJsonAsync<bool>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/ReadAllTicketMessages?ticketId={ticketId}");
                    NavSideBar();
                    return Page();
                }
                else
                {
                    Message = $"تیکت مورد نظر یا بسته شده و یا در سطل زباله هست";
                    return RedirectToPage("TicketsList");
                }
            }
        }

        public async Task<Users> GetUserByIdAsync(int userId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                return await httpClient.GetFromJsonAsync<Users>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetUserById?userId={userId}");
            }
        }

        public async Task<IActionResult> OnGetDeleteTicketAsync(int ticketId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                await httpClient.DeleteAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/DeleteTicket?ticketId={ticketId}");
                Ticketings ticket = await httpClient.GetFromJsonAsync<Ticketings>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketById?ticketId={ticketId}");
                Message = $"تیکت '{ticket.Title}' با موفقیت به سطل زباله انتقال یافت";
            }
            return RedirectToPage("TicketsList");
        }

        public async Task<IActionResult> OnGetCloseTicketAsync(int ticketId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                Ticketings ticket = await httpClient.GetFromJsonAsync<Ticketings>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketById?ticketId={ticketId}");
                await httpClient.PutAsJsonAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/CloseTicket", ticket);
                Message = $"تیکت '{ticket.Title}' با موفقیت بسته و غیرفعال شد";
            }
            return RedirectToPage("TicketsList");
        }

        public async Task<IActionResult> OnPostAnswerTicketAsync()
        {
            TicketMessage.IsSeen = false;
            TicketMessage.CreatedOn = DateTime.Now;
            using (HttpClient httpClient = new HttpClient())
            {
                Ticketings ticket = await httpClient.GetFromJsonAsync<Ticketings>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketById?ticketId={TicketMessage.TicketId}");
                await httpClient.PostAsJsonAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/SendTicketMessageByAdmin", TicketMessage);
                Message = $"تیکت '{ticket.Title}' با موفقیت پاسخ داده شد";
            }
            return RedirectToPage("TicketsList");
        }

        private void NavSideBar()
        {
            ViewData["support"] = true;
            ViewData["listTicket"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/Ticket/ClosedTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Application.ViewModels.Public;
using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.Ticket
{
    public class ClosedTicketModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public IList<Ticketings> Ticketings { get; set; }

        public IConfiguration Configuration { get; set; }

        public PaggingViewModel PaggingViewModel { get; set; }

        public ClosedTicketModel(IConfiguration configuration, PaggingViewModel paggingViewModel)
        {
            Configuration = configuration;
            PaggingViewModel = paggingViewModel;
        }
        public async Task OnGetAsync(string query, int pageId = 1)
        {
            if (!string.IsNullOrEmpty(query) || !string.IsNullOrWhiteSpace(query))
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Ticketings = await httpClient.GetFromJsonAsync<IList<Ticketings>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/FilterClosedTickets?query={query}&pageId={pageId}");
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(await httpClient.GetFromJsonAsync<double>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/FilterClosedTicketsCount?query={query}") / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
                ViewData["query"] = query;
            }
            else
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Ticketings = await httpClient.GetFromJsonAsync<IList<Ticketings>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetClosedTickets?pageId={pageId}");
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(await httpClient.GetFromJsonAsync<double>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetClosedTicketsCount") / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
            }

            NavSideBar();
        }

        public async Task<Users> GetUserByIdAsync(int userId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                return await httpClient.GetFromJsonAsync<Users>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetUserById?userId={userId}");
            }
        }

        public async Task<IActionResult> OnGetReOpenTicketAsync(int ticketId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                Ticketings ticket = await httpClient.GetFromJsonAsync<Ticketings>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketById?ticketId={ticketId}");
                await httpClient.PutAsJsonAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/OpenTicket", ticket);
                Message = $"تیکت '{ticket.Title}' با موفقیت باز و فعال شد";
            }
            return RedirectToPage("TicketsList");
        }

        private void NavSideBar()
        {
            ViewData["support"] = true;
            ViewData["listTicket"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/Ticket/ContactUsTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Application.ViewModels.Public;
using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.Ticket
{
    public class ContactUsTicketModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public IList<ContactUs> ContactUs { get; set; }

        public IConfiguration Configuration { get; set; }

        public PaggingViewModel PaggingViewModel { get; set; }

        public ContactUsTicketModel(IConfiguration configuration, PaggingViewModel paggingViewModel)
        {
            Configuration = configuration;
            PaggingViewModel = paggingViewModel;
        }

        public async Task OnGetAsync(string query, int pageId = 1)
        {
            if (!string.IsNullOrEmpty(query) || !string.IsNullOrWhiteSpace(query))
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Tuple<IList<ContactUs>, int> contactUsResponse = await httpClient.GetFromJsonAsync<Tuple<IList<ContactUs>, int>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetAllContactUs?query={query}&pageId={pageId}");
                    ContactUs = contactUsResponse.Item1;
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(contactUsResponse.Item2 / 50.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
                ViewData["query"] = query;
            }
            else
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Tuple<IList<ContactUs>, int> contactUsResponse = await httpClient.GetFromJsonAsync<Tuple<IList<ContactUs>, int>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetAllContactUs?pageId={pageId}");
                    ContactUs = contactUsResponse.Item1;
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(contactUsResponse.Item2 / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
            }

            NavSideBar();
        }

        public async Task<IActionResult> OnPostAsync(int contactUsId, string answerText)
        {
            using HttpClient httpClient = new HttpClient();
            ContactUs contactUs = await httpClient.GetFromJsonAsync<ContactUs>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetContactUs?id={contactUsId}");
            await httpClient.PostAsJsonAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/AnswerContactUs", new ContactUsRequest() { ContactId = contactUsId, Answer = answerText });
            Message = $"پاسخ تیکت {contactUs.Subject} با موفقیت ارسال شد";
            return RedirectToPage("ContactUsTicket");
        }

        private void NavSideBar()
        {
            ViewData["support"] = true;
            ViewData["listTicket"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/Ticket/DeletedTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

using ThemeShop.Application.ViewModels.Public;
using ThemeShop.Domain.Models;

namespace AdminModule.Areas.Admin.Pages.Ticket
{
    public class DeletedTicketModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public IList<Ticketings> Ticketings { get; set; }

        public IConfiguration Configuration { get; set; }

        public PaggingViewModel PaggingViewModel { get; set; }

        public DeletedTicketModel(IConfiguration configuration, PaggingViewModel paggingViewModel)
        {
            Configuration = configuration;
            PaggingViewModel = paggingViewModel;
        }

        public async Task OnGetAsync(string query, int pageId = 1)
        {
            if (!string.IsNullOrEmpty(query) || !string.IsNullOrWhiteSpace(query))
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Ticketings = await httpClient.GetFromJsonAsync<IList<Ticketings>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/FilterDeletedTickets?query={query}&pageId={pageId}");
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(await httpClient.GetFromJsonAsync<double>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/FilterDeletedTicketsCount?query={query}") / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
                ViewData["query"] = query;
            }
            else
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    Ticketings = await httpClient.GetFromJsonAsync<IList<Ticketings>>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetDeletedTickets?pageId={pageId}");
                    //Pagging
                    PaggingViewModel.ActivePage = pageId;
                    PaggingViewModel.PageCount = (int)Math.Ceiling(await httpClient.GetFromJsonAsync<double>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetDeletedTicketsCount") / 30.00);
                    PaggingViewModel.ParametrUrlName = "pageId";
                    PaggingViewModel.Query = query;
                }
            }

            NavSideBar();
        }

        public async Task<Users> GetUserByIdAsync(int userId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                return await httpClient.GetFromJsonAsync<Users>($"{Configuration.GetSection("ApiUrlAddress").Value}/User/GetUserById?userId={userId}");
            }
        }

        public async Task<IActionResult> OnGetRecoverTicketAsync(int ticketId)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                Ticketings ticket = await httpClient.GetFromJsonAsync<Ticketings>($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/GetTicketById?ticketId={ticketId}");
                await httpClient.PutAsJsonAsync($"{Configuration.GetSection("ApiUrlAddress").Value}/Ticket/RecoverTicket", ticket);
                Message = $"تیکت '{ticket.Title}' با موفقیت باز و فعال شد";
            }
            return RedirectToPage("DeletedTicket");
        }

        private void NavSideBar()
        {
            ViewData["support"] = true;
            ViewData["listTicket"] = true;
        }
    }
}

AdminModule/Areas/Admin/Pages/Ticket/AnswerTicket.cshtml
@page
@model AdminModule.Areas.Admin.Pages.Ticket.AnswerTicketModel
@{
    ViewData["Title"] = $"پاسخ تیکت {Model.Ticket.Title}";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>پاسخ تیکت</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-page="/Ticket/TicketsList">تیکت</a></li>
                    <li class="breadcrumb-item active">پاسخ تیکت</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>



<section class="content">
    <div class="row">
        @await Component.InvokeAsync("TicketBoxComponent")
        <div class="card card-primary card-outline direct-chat direct-chat-primary col-md-9 p-0">
            <div class="card-header">
                <h3 class="card-title">موضوع تیکت : @Model.Ticket.Title</h3>

                <div class="card-tools position-relative float-rigt mt-2">
                    @if (Model.Ticket.IsClose || Model.Ticket.IsDelete)
                    {

                    }
                    else
                    {
                        <a asp-page-handler="DeleteTicket" asp-route-ticketId="@Model.Ticket.TicketId">
                            <i class="bg-danger p-2 text-white fa fa-trash-o rounded"><span style="font-family: 'Vazir';"> حذف</span></i>
                        </a>
                        <a asp-page-handler="CloseTicket" asp-route-ticketId="@Model.Ticket.TicketId">
                            <i class="bg-warning p-2 text-white fa fa-close rounded"><span style="font-family: 'Vazir';"> بستن تیکت</span></i>
                        </a>
                    }
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <!-- Conversations are loaded here -->
                <div class="direct-chat-messages min-height-ticket-message">
                    @foreach (var message in Model.TicketMessages)
                    {
                        if (message.UserId == Model.Ticket.Sender)
                        {
                            <!-- Message. Default to the left -->
                            <div class="direct-chat-msg">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name float-left">@Model.Sender.UserName</span>
                                    <span class="direct-chat-timestamp float-right">@message.CreatedOn.ToLongShamsiDate()</span>
                                </div>
                                <!-- /.direct-chat-info -->
                                <img class="direct-chat-img" src="@Model.Sender.Avatar" alt="@Model.Sender.Name">
                                <!-- /.direct-chat-img -->
                                <div class="direct-chat-text">
                                    @message.Text
                                </div>
                                <!-- /.direct-chat-text -->
                            </div>
                            <!-- /.direct-chat-msg -->
                        }
                        else
                        {
                            <!-- Message to the right -->
                            <div class="direct-chat-msg right">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name float-right">@Model.Reciver.UserName</span>
                                    <span class="direct-chat-timestamp float-left">@message.CreatedOn.ToLongShamsiDate()</span>
                                </div>
                                <!-- /.direct-chat-info -->
                                <img class="direct-chat-img" src="@Model.Reciver.Avatar" alt="@Model.Reciver.Name">
                                <!-- /.direct-chat-img -->
                                <div class="direct-chat-text">
                                    @Html.Raw(message.Text)
                                </div>
                                <!-- /.direct-chat-text -->
                            </div>
                            <!-- /.direct-chat-msg -->
                        }
                    }


                </div>
                <!--/.direct-chat-messages-->
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <form method="post">
                    <div>
                        <input asp-for="TicketMessage.UserId" value="@Model.Ticket.Reciver" type="hidden" hidden />
                        <input asp-for="TicketMessage.TicketId" value="@Model.Ticket.TicketId" type="hidden" hidden />
                        <input asp-for="TicketMessage.OwnerId" value="@Model.Ticket.Reciver" type="hidden" hidden />
                        <label>متن پاسخ :</label>
                        <textarea id="answerText" asp-for="TicketMessage.Text" placeholder="تایپ پیام ..." class="form-control"></textarea>
                    </div>
                    <button asp-page-handler="AnswerTicket" type="submit" class="btn btn-primary mt-3">ارسال</button>
                </form>
            </div>
            <!-- /.card-footer-->
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/admin/lib/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('answerText', {
            customConfig: '/admin/lib/ckeditor/config-tickets.js'
        });
    </script>
}

AdminModule/Areas/Admin/Pages/Ticket/ClosedTicket.cshtml
@page
@model AdminModule.Areas.Admin.Pages.Ticket.ClosedTicketModel
@{
    ViewData["Title"] = "لیست تیکت ها بسته شده";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>لیست تیکت ها بسته شده</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-page="/Ticket/TicketsList">تیکت</a></li>
                    <li class="breadcrumb-item active">تیکت ها بسته شده</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        @await Component.InvokeAsync("TicketBoxComponent")
        <!-- /.col -->
        <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">تیکت ها بسته شده</h3>

                    <div class="card-tools">
                        <form method="get">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="query" class="form-control float-right" placeholder="جستجو تیکت" @((ViewData["query"] != null) ? $"value={ViewData["query"]}" : "")>
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-tools -->
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>عملیات</th>
                                    <th>وضعیت</th>
                                    <th>فرستنده</th>
                                    <th>عنوان</th>
                                    <th>تاریخ ایجاد</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Ticketings != null)
                                {
                                    @foreach (var ticket in Model.Ticketings)
                                    {
                                        Users sender = await Model.GetUserByIdAsync(ticket.Sender);
                                        <tr>
                                            <td>
                                                <a asp-page-handler="ReOpenTicket" asp-route-ticketId="@ticket.TicketId"><i class="bg-danger p-2 text-white fa fa-folder-open-o rounded"><span style="font-family: 'Vazir';"> باز کردن</span></i></a>
                                                <a asp-area="Admin" asp-page="/Ticket/AnswerTicket" asp-route-ticketId="@ticket.TicketId"><i class="bg-success p-2 text-white fa fa-eye rounded"><span style="font-family: 'Vazir';"> مشاهده</span></i></a>
                                            </td>
                                            <td><i class="bg-info p-2 text-white fa fa-close rounded"><span style="font-family: 'Vazir';"> بسته شده</span></i></td>
                                            <td class="mailbox-name"><a asp-area="Admin" asp-page="/User/UsersList" asp-route-query="@sender.UserName">@sender.UserName</a></td>
                                            <td class="mailbox-subject">
                                                <a asp-area="Admin" asp-page="/Ticket/AnswerTicket" asp-route-ticketId="@ticket.TicketId"><b>@ticket.Title</b></a>
                                            </td>
                                            <td class="mailbox-date">@ticket.CreatedOn.ToLongShamsiDate()</td>
                                        </tr>
                                    }

                                }
                            </tbody>
                        </table>
                        <!-- /.table -->
                    </div>
                    <!-- /.mail-box-messages -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer p-0">
                    <div class="mailbox-controls">
                        <!-- Check all button -->
                        @await Component.InvokeAsync("PaginationComponent", Model.PaggingViewModel)
                        <!-- /.float-right -->
                    </div>
                </div>
            </div>
            <!-- /. box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

AdminModule/Areas/Admin/Pages/Ticket/DeletedTicket.cshtml
@page
@model AdminModule.Areas.Admin.Pages.Ticket.DeletedTicketModel
@{
    ViewData["Title"] = "لیست تیکت ها حذف شده";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>لیست تیکت ها حذف شده</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-area="Admin" asp-page="/Ticket/TicketsList">تیکت</a></li>
                    <li class="breadcrumb-item active">تیکت ها حذف شده</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="row">
        @await Component.InvokeAsync("TicketBoxComponent")
        <!-- /.col -->
        <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">تیکت ها حذف شده</h3>

                    <div class="card-tools">
                        <form method="get">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="query" class="form-control float-right" placeholder="جستجو تیکت" @((ViewData["query"] != null) ? $"value={ViewData["query"]}" : "")>
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-tools -->
                </div>
                <!-- /.card-header -->
                <div class="card-body p-0">
                    <div class="table-responsive mailbox-messages">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>عملیات</th>
                                    <th>وضعیت</th>
                                    <th>فرستنده</th>
                                    <th>عنوان</th>
                                    <th>تاریخ ایجاد</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Ticketings != null)
                                {
                                    @foreach (var ticket in Model.Ticketings)
                                    {
                                        Users sender = await Model.GetUserByIdAsync(ticket.Sender);
                                        <tr>
                                            <td>
                                                <a asp-page-handler="RecoverTicket" asp-route-ticketId="@ticket.TicketId"><i class="bg-success p-2 text-white fa fa-check-circle-o rounded"><span style="font-family: 'Vazir';"> فعال کردن</span></i></a>
                                            </td>
                                            <td><i class="bg-danger p-2 text-white fa fa-trash-o rounded"><span style="font-family: 'Vazir';"> حذف شده</span></i></td>
                                            <td class="mailbox-name"><a asp-area="Admin" asp-page="/User/UsersList" asp-route-query="@sender.UserName">@sender.UserName</a></td>
                                            <td class="mailbox-subject">
                                                <a asp-area="Admin" asp-page="/Ticket/AnswerTicket" asp-route-ticketId="@ticket.TicketId"><b>@ticket.Title</b></a>
                                            </td>
                                            <td class="mailbox-date">@ticket.CreatedOn.ToLongShamsiDate()</td>
                                        </tr>
                                    }

                                }
                            </tbody>
                        </table>
                        <!-- /.table -->
                    </div>
                    <!-- /.mail-box-messages -->
                </div>
                <!-- /.card-body -->
                <div class="card-footer p-0">
                    <div class="mailbox-controls">
                        <!-- Check all button -->
                        @await Component.InvokeAsync("PaginationComponent", Model.PaggingViewModel)
                        <!-- /.float-right -->
                    </div>
                </div>
            </div>
            <!-- /. box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

@if (!string.IsNullOrEmpty(Model.Message))
{
    <input type="hidden" id="message" value="@Model.Message" />
}

@section Scripts{
    <script>
        var message = $('#message').val(); // get the value of the message
        if (message != null && message != "") {
            swal({
                title: "تیکت ها",
                buttons: false,
                timer: 3000,
                text: message,
                icon: "success"
            });
        }
    </script>
}